export const MODELS = {
  stt: {
    deepgram: {
      name: "Deepgram",
      models: {
        "flux-general-en": {
          name: "Flux",
          languages: ["en"],
          usdPerMinute: 0.0065,
        },
        "flux-general-multi": {
          name: "Flux (Multilingual)",
          usdPerMinute: 0.0078,
          languages: [
            "multi",
            "en",
            "es",
            "fr",
            "de",
            "hi",
            "ru",
            "pt",
            "ja",
            "it",
            "nl",
          ],
        },
        "nova-3": {
          name: "Nova-3",
          usdPerMinute: 0.0058,
          languages: [
            "ar",
            "ar-AE",
            "ar-SA",
            "ar-QA",
            "ar-KW",
            "ar-SY",
            "ar-LB",
            "ar-PS",
            "ar-JO",
            "ar-EG",
            "ar-SD",
            "ar-TD",
            "ar-MA",
            "ar-DZ",
            "ar-TN",
            "ar-IQ",
            "ar-IR",
            "be",
            "bn",
            "bs",
            "bg",
            "ca",
            "hr",
            "cs",
            "da",
            "da-DK",
            "nl",
            "nl-BE",
            "en",
            "en-US",
            "en-AU",
            "en-GB",
            "en-IN",
            "en-NZ",
            "et",
            "fi",
            "fr",
            "fr-CA",
            "de",
            "de-CH",
            "el",
            "hi",
            "hu",
            "id",
            "it",
            "ja",
            "kn",
            "ko",
            "ko-KR",
            "lv",
            "lt",
            "mk",
            "ms",
            "mr",
            "no",
            "pl",
            "pt",
            "pt-BR",
            "pt-PT",
            "ro",
            "ru",
            "sr",
            "sk",
            "sl",
            "es",
            "es-419",
            "sv",
            "sv-SE",
            "tl",
            "ta",
            "te",
            "tr",
            "uk",
            "vi",
            "zh",
            "zh-CN",
            "zh-Hans",
            "zh-TW",
            "zh-Hant",
            "zh-HK",
            "multi",
          ],
        },
        "nova-3-medical": {
          name: "Nova-3 Medical",
          usdPerMinute: 0.0077,
          languages: [
            "en",
            "en-US",
            "en-AU",
            "en-CA",
            "en-GB",
            "en-IE",
            "en-IN",
            "en-NZ",
          ],
        },
        "nova-2": {
          name: "Nova-2",
          usdPerMinute: 0.0058,
          languages: [
            "multi",
            "bg",
            "ca",
            "zh",
            "zh-CN",
            "zh-Hans",
            "zh-TW",
            "zh-Hant",
            "zh-HK",
            "cs",
            "da",
            "da-DK",
            "nl",
            "nl-BE",
            "en",
            "en-US",
            "en-AU",
            "en-GB",
            "en-NZ",
            "en-IN",
            "et",
            "fi",
            "fr",
            "fr-CA",
            "de",
            "de-CH",
            "el",
            "hi",
            "hu",
            "id",
            "it",
            "ja",
            "ko",
            "ko-KR",
            "lv",
            "lt",
            "ms",
            "no",
            "pl",
            "pt",
            "pt-BR",
            "pt-PT",
            "ro",
            "ru",
            "sk",
            "es",
            "es-419",
            "sv",
            "sv-SE",
            "th",
            "th-TH",
            "tr",
            "uk",
            "vi",
          ],
        },
        "nova-2-conversationalai": {
          name: "Nova-2 Conversational AI",
          usdPerMinute: 0.0058,
          languages: ["en", "en-US"],
        },
        "nova-2-medical": {
          name: "Nova-2 Medical",
          usdPerMinute: 0.0058,
          languages: ["en", "en-US"],
        },
        "nova-2-phonecall": {
          name: "Nova-2 Phone Call",
          usdPerMinute: 0.0058,
          languages: ["en", "en-US"],
        },
      },
    },
    assemblyai: {
      name: "AssemblyAI",
      models: {
        "u3-rt-pro": {
          name: "Universal-3 Pro Streaming",
          usdPerMinute: 0.0075,
          languages: [
            "en",
            "en-US",
            "en-GB",
            "en-AU",
            "en-CA",
            "en-IN",
            "en-NZ",
            "es",
            "es-ES",
            "es-MX",
            "es-AR",
            "es-CO",
            "es-CL",
            "es-PE",
            "es-VE",
            "es-EC",
            "es-GT",
            "es-CU",
            "es-BO",
            "es-DO",
            "es-HN",
            "es-PY",
            "es-SV",
            "es-NI",
            "es-CR",
            "es-PA",
            "es-UY",
            "es-PR",
            "fr",
            "fr-FR",
            "fr-CA",
            "fr-BE",
            "fr-CH",
            "de",
            "de-DE",
            "de-AT",
            "de-CH",
            "it",
            "it-IT",
            "it-CH",
            "pt",
            "pt-BR",
            "pt-PT",
          ],
        },
        "universal-3-5-pro": {
          name: "Universal-3.5 Pro Streaming",
          usdPerMinute: 0.0075,
          languages: [
            "en",
            "en-US",
            "en-GB",
            "en-AU",
            "en-CA",
            "en-IN",
            "en-NZ",
            "es",
            "es-ES",
            "es-MX",
            "es-AR",
            "es-CO",
            "es-CL",
            "es-PE",
            "es-VE",
            "es-EC",
            "es-GT",
            "es-CU",
            "es-BO",
            "es-DO",
            "es-HN",
            "es-PY",
            "es-SV",
            "es-NI",
            "es-CR",
            "es-PA",
            "es-UY",
            "es-PR",
            "fr",
            "fr-FR",
            "fr-CA",
            "fr-BE",
            "fr-CH",
            "de",
            "de-DE",
            "de-AT",
            "de-CH",
            "it",
            "it-IT",
            "it-CH",
            "pt",
            "pt-BR",
            "pt-PT",
            "tr",
            "nl",
            "sv",
            "no",
            "da",
            "fi",
            "hi",
            "vi",
            "ar",
            "he",
            "ja",
            "ur",
            "zh",
          ],
        },
        "universal-streaming": {
          name: "Universal-Streaming",
          usdPerMinute: 0.0025,
          languages: ["en", "en-US"],
        },
        "universal-streaming-multilingual": {
          name: "Universal-Streaming-Multilingual",
          usdPerMinute: 0.0025,
          languages: [
            "multi",
            "en",
            "en-US",
            "en-GB",
            "en-AU",
            "en-CA",
            "en-IN",
            "en-NZ",
            "es",
            "es-ES",
            "es-MX",
            "es-AR",
            "es-CO",
            "es-CL",
            "es-PE",
            "es-VE",
            "es-EC",
            "es-GT",
            "es-CU",
            "es-BO",
            "es-DO",
            "es-HN",
            "es-PY",
            "es-SV",
            "es-NI",
            "es-CR",
            "es-PA",
            "es-UY",
            "es-PR",
            "fr",
            "fr-FR",
            "fr-CA",
            "fr-BE",
            "fr-CH",
            "de",
            "de-DE",
            "de-AT",
            "de-CH",
            "it",
            "it-IT",
            "it-CH",
            "pt",
            "pt-BR",
            "pt-PT",
          ],
        },
      },
    },
    cartesia: {
      name: "Cartesia",
      models: {
        "ink-2": { name: "Ink 2", languages: ["en"], usdPerMinute: 0.009 },
        "ink-whisper": {
          name: "Ink Whisper",
          usdPerMinute: 0.003,
          languages: [
            "en",
            "zh",
            "de",
            "es",
            "ru",
            "ko",
            "fr",
            "ja",
            "pt",
            "tr",
            "pl",
            "ca",
            "nl",
            "ar",
            "sv",
            "it",
            "id",
            "hi",
            "fi",
            "vi",
            "he",
            "uk",
            "el",
            "ms",
            "cs",
            "ro",
            "da",
            "hu",
            "ta",
            "no",
            "th",
            "ur",
            "hr",
            "bg",
            "lt",
            "la",
            "mi",
            "ml",
            "cy",
            "sk",
            "te",
            "fa",
            "lv",
            "bn",
            "sr",
            "az",
            "sl",
            "kn",
            "et",
            "mk",
            "br",
            "eu",
            "is",
            "hy",
            "ne",
            "mn",
            "bs",
            "kk",
            "sq",
            "sw",
            "gl",
            "mr",
            "pa",
            "si",
            "km",
            "sn",
            "yo",
            "so",
            "af",
            "oc",
            "ka",
            "be",
            "tg",
            "sd",
            "gu",
            "am",
            "yi",
            "lo",
            "uz",
            "fo",
            "ht",
            "ps",
            "tk",
            "nn",
            "mt",
            "sa",
            "lb",
            "my",
            "bo",
            "tl",
            "mg",
            "as",
            "tt",
            "haw",
            "ln",
            "ha",
            "ba",
            "jw",
            "su",
            "yue",
          ],
        },
      },
    },
    elevenlabs: {
      name: "ElevenLabs",
      models: {
        scribe_v2_realtime: {
          name: "Scribe v2 Realtime",
          usdPerMinute: 0.0105,
          languages: [
            "af",
            "afr",
            "am",
            "amh",
            "ar",
            "ara",
            "as",
            "asm",
            "az",
            "azj",
            "be",
            "bel",
            "bg",
            "bul",
            "bn",
            "ben",
            "bs",
            "bos",
            "my",
            "mya",
            "ca",
            "cat",
            "cs",
            "ces",
            "ny",
            "nya",
            "cy",
            "cym",
            "da",
            "dan",
            "de",
            "deu",
            "el",
            "ell",
            "en",
            "eng",
            "es",
            "spa",
            "et",
            "est",
            "fa",
            "fas",
            "ff",
            "ful",
            "fi",
            "fin",
            "fr",
            "fra",
            "ga",
            "gle",
            "gl",
            "glg",
            "lg",
            "lug",
            "ka",
            "kat",
            "gu",
            "guj",
            "ha",
            "hau",
            "he",
            "heb",
            "hi",
            "hin",
            "hr",
            "hrv",
            "hu",
            "hun",
            "hy",
            "hye",
            "id",
            "ind",
            "ig",
            "ibo",
            "is",
            "isl",
            "it",
            "ita",
            "ja",
            "jpn",
            "jv",
            "jav",
            "kk",
            "kaz",
            "km",
            "khm",
            "kn",
            "kan",
            "ko",
            "kor",
            "ku",
            "kur",
            "ky",
            "kir",
            "lb",
            "ltz",
            "ln",
            "lin",
            "lo",
            "lao",
            "lt",
            "lit",
            "lv",
            "lav",
            "mi",
            "mri",
            "mk",
            "mkd",
            "ml",
            "mal",
            "mn",
            "mon",
            "mr",
            "mar",
            "ms",
            "msa",
            "mt",
            "mlt",
            "ne",
            "nep",
            "nl",
            "nld",
            "no",
            "nor",
            "oc",
            "oci",
            "or",
            "ori",
            "pa",
            "pan",
            "pl",
            "pol",
            "ps",
            "pus",
            "pt",
            "por",
            "ro",
            "ron",
            "ru",
            "rus",
            "sr",
            "srp",
            "sd",
            "snd",
            "sk",
            "slk",
            "sl",
            "slv",
            "sn",
            "sna",
            "so",
            "som",
            "sv",
            "swe",
            "sw",
            "swa",
            "ta",
            "tam",
            "te",
            "tel",
            "tg",
            "tgk",
            "th",
            "tha",
            "tr",
            "tur",
            "uk",
            "ukr",
            "ur",
            "urd",
            "uz",
            "uzb",
            "vi",
            "vie",
            "wo",
            "wol",
            "xh",
            "xho",
            "zh",
            "zho",
            "zu",
            "zul",
            "ast",
            "ceb",
            "fil",
            "kea",
            "luo",
            "nso",
            "umb",
            "yue",
          ],
        },
      },
    },
    speechmatics: {
      name: "Speechmatics",
      models: {
        enhanced: {
          name: "Speechmatics Enhanced",
          usdPerMinute: 0.0117,
          languages: [
            "ar",
            "ar_en",
            "ba",
            "be",
            "bg",
            "bn",
            "ca",
            "cmn",
            "cmn_en",
            "cmn_en_ms_ta",
            "cs",
            "cy",
            "da",
            "de",
            "el",
            "en",
            "en_ms",
            "en_ta",
            "eo",
            "es",
            "et",
            "eu",
            "fa",
            "fi",
            "fr",
            "ga",
            "gl",
            "he",
            "hi",
            "hr",
            "hu",
            "ia",
            "id",
            "it",
            "ja",
            "ko",
            "lt",
            "lv",
            "mn",
            "mr",
            "ms",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "ru",
            "sk",
            "sl",
            "sv",
            "sw",
            "ta",
            "th",
            "tl",
            "tr",
            "ug",
            "uk",
            "ur",
            "vi",
            "yue",
          ],
        },
        standard: {
          name: "Speechmatics Standard",
          usdPerMinute: 0.005,
          languages: [
            "ar",
            "ar_en",
            "ba",
            "be",
            "bg",
            "bn",
            "ca",
            "cmn",
            "cmn_en",
            "cmn_en_ms_ta",
            "cs",
            "cy",
            "da",
            "de",
            "el",
            "en",
            "en_ms",
            "en_ta",
            "eo",
            "es",
            "et",
            "eu",
            "fa",
            "fi",
            "fr",
            "ga",
            "gl",
            "he",
            "hi",
            "hr",
            "hu",
            "ia",
            "id",
            "it",
            "ja",
            "ko",
            "lt",
            "lv",
            "mn",
            "mr",
            "ms",
            "mt",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "ru",
            "sk",
            "sl",
            "sv",
            "sw",
            "ta",
            "th",
            "tl",
            "tr",
            "ug",
            "uk",
            "ur",
            "vi",
            "yue",
            "xAI",
          ],
        },
      },
    },
    xai: {
      name: "xAI",
      models: {
        "stt-1": {
          name: "Speech to Text",
          usdPerMinute: 0.0033,
          languages: [
            "en",
            "ar",
            "cs",
            "da",
            "nl",
            "fr",
            "de",
            "hi",
            "id",
            "it",
            "ja",
            "ko",
            "ms",
            "fa",
            "pl",
            "pt",
            "ro",
            "ru",
            "es",
            "sv",
            "th",
            "tr",
            "vi",
            "fil",
            "mk",
          ],
        },
      },
    },
  },
  llm: {
    "deepseek-ai": {
      name: "DeepSeek",
      models: {
        "deepseek-v4-pro": { name: "DeepSeek-V4 Pro", usdPerMinute: 0.0058 },
      },
    },
    google: {
      name: "Google",
      models: {
        "gemini-2.5-flash": {
          name: "Gemini 2.5 Flash",
          usdPerMinute: 0.0013,
        },
        "gemini-2.5-flash-lite": {
          name: "Gemini 2.5 Flash-Lite",
          usdPerMinute: 0.0004,
        },
        "gemini-2.5-pro": { name: "Gemini 2.5 Pro", usdPerMinute: 0.0101 },
        "gemini-3-flash-preview": {
          name: "Gemini 3 Flash",
          usdPerMinute: 0.002,
        },
        "gemini-3.1-flash-lite": {
          name: "Gemini 3.1 Flash Lite",
          usdPerMinute: 0.001,
        },
        "gemini-3.1-pro-preview": {
          name: "Gemini 3.1 Pro",
          usdPerMinute: 0.0152,
        },
        "gemini-3.5-flash": {
          name: "Gemini 3.5 Flash",
          usdPerMinute: 0.0061,
        },
      },
    },
    moonshotai: {
      name: "Moonshot AI",
      models: {
        "kimi-k2.5": { name: "Kimi K2.5", usdPerMinute: 0.0023 },
      },
    },
    openai: {
      name: "OpenAI",
      models: {
        "chat-latest": { name: "ChatGPT Latest", usdPerMinute: 0.0203 },
        "gpt-4.1": { name: "GPT-4.1", usdPerMinute: 0.0074 },
        "gpt-4.1-mini": { name: "GPT-4.1 mini", usdPerMinute: 0.0015 },
        "gpt-4.1-nano": { name: "GPT-4.1 nano", usdPerMinute: 0.0004 },
        "gpt-4o": { name: "GPT-4o", usdPerMinute: 0.0093 },
        "gpt-4o-mini": { name: "GPT-4o mini", usdPerMinute: 0.0006 },
        "gpt-5": { name: "GPT-5", usdPerMinute: 0.0055 },
        "gpt-5-mini": { name: "GPT-5 mini", usdPerMinute: 0.0011 },
        "gpt-5-nano": { name: "GPT-5 nano", usdPerMinute: 0.0002 },
        "gpt-5.1": { name: "GPT-5.1", usdPerMinute: 0.0055 },
        "gpt-5.2": { name: "GPT-5.2", usdPerMinute: 0.0077 },
        "gpt-5.4": { name: "GPT-5.4", usdPerMinute: 0.0189 },
        "gpt-5.4-mini": { name: "GPT-5.4 mini", usdPerMinute: 0.003 },
        "gpt-5.4-nano": { name: "GPT-5.4 nano", usdPerMinute: 0.0008 },
        "gpt-5.5": { name: "GPT-5.5", usdPerMinute: 0.0379 },
        "gpt-oss-120b": { name: "GPT OSS 120B", usdPerMinute: 0.0006 },
      },
    },
    xai: {
      name: "xAI",
      models: {
        "grok-4-1-fast-non-reasoning": {
          name: "Grok 4.1 Fast",
          usdPerMinute: 0.0007,
        },
        "grok-4-1-fast-reasoning": {
          name: "Grok 4.1 Fast Reasoning",
          usdPerMinute: 0.0007,
        },
        "grok-4.20-0309-non-reasoning": {
          name: "Grok 4.20",
          usdPerMinute: 0.007,
        },
        "grok-4.20-0309-reasoning": {
          name: "Grok 4.20 Reasoning",
          usdPerMinute: 0.007,
        },
        "grok-4.20-multi-agent-0309": {
          name: "Grok 4.20 Multi-Agent",
          usdPerMinute: 0.007,
        },
      },
    },
  },
  tts: {
    cartesia: {
      name: "Cartesia",
      models: {
        "sonic-2": {
          name: "Sonic 2",
          usdPerMinute: 0.03,
          languages: ["en", "fr", "de", "es", "pt", "zh", "ja", "ko"],
        },
        "sonic-3": {
          name: "Sonic 3",
          usdPerMinute: 0.03,
          languages: [
            "en",
            "de",
            "es",
            "fr",
            "ja",
            "pt",
            "zh",
            "hi",
            "ko",
            "it",
            "nl",
            "pl",
            "ru",
            "sv",
            "tr",
            "tl",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "hu",
            "no",
            "vi",
            "bn",
            "th",
            "he",
            "ka",
            "id",
            "te",
            "gu",
            "kn",
            "ml",
            "mr",
            "pa",
          ],
        },
        "sonic-3-2025-10-27": {
          name: "Sonic 3 (2025-10-27)",
          usdPerMinute: 0.03,
          languages: [
            "en",
            "de",
            "es",
            "fr",
            "ja",
            "pt",
            "zh",
            "hi",
            "ko",
            "it",
            "nl",
            "pl",
            "ru",
            "sv",
            "tr",
            "tl",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "hu",
            "no",
            "vi",
            "bn",
            "th",
            "he",
            "ka",
            "id",
            "te",
            "gu",
            "kn",
            "ml",
            "mr",
            "pa",
          ],
        },
        "sonic-3-2026-01-12": {
          name: "Sonic 3 (2026-01-12)",
          usdPerMinute: 0.03,
          languages: [
            "en",
            "de",
            "es",
            "fr",
            "ja",
            "pt",
            "zh",
            "hi",
            "ko",
            "it",
            "nl",
            "pl",
            "ru",
            "sv",
            "tr",
            "tl",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "hu",
            "no",
            "vi",
            "bn",
            "th",
            "he",
            "ka",
            "id",
            "te",
            "gu",
            "kn",
            "ml",
            "mr",
            "pa",
          ],
        },
        "sonic-3-latest": {
          name: "Sonic 3 Latest",
          usdPerMinute: 0.03,
          languages: [
            "en",
            "de",
            "es",
            "fr",
            "ja",
            "pt",
            "zh",
            "hi",
            "ko",
            "it",
            "nl",
            "pl",
            "ru",
            "sv",
            "tr",
            "tl",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "hu",
            "no",
            "vi",
            "bn",
            "th",
            "he",
            "ka",
            "id",
            "te",
            "gu",
            "kn",
            "ml",
            "mr",
            "pa",
          ],
        },
        "sonic-3.5": {
          name: "Sonic 3.5",
          usdPerMinute: 0.03,
          languages: [
            "en",
            "de",
            "es",
            "ja",
            "pt",
            "zh",
            "hi",
            "ko",
            "nl",
            "pl",
            "ru",
            "sv",
            "tr",
            "tl",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "hu",
            "no",
            "vi",
            "bn",
            "th",
            "he",
            "ka",
            "id",
            "te",
            "gu",
            "kn",
            "ml",
            "mr",
            "pa",
          ],
        },
        "sonic-3.5-2026-05-04": {
          name: "Sonic 3.5 (2026-05-04)",
          usdPerMinute: 0.03,
          languages: [
            "en",
            "de",
            "es",
            "ja",
            "pt",
            "zh",
            "hi",
            "ko",
            "nl",
            "pl",
            "ru",
            "sv",
            "tr",
            "tl",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "hu",
            "no",
            "vi",
            "bn",
            "th",
            "he",
            "ka",
            "id",
            "te",
            "gu",
            "kn",
            "ml",
            "mr",
            "pa",
          ],
        },
        "sonic-latest": {
          name: "Sonic Latest",
          usdPerMinute: 0.03,
          languages: [
            "en",
            "de",
            "es",
            "ja",
            "pt",
            "zh",
            "hi",
            "ko",
            "nl",
            "pl",
            "ru",
            "sv",
            "tr",
            "tl",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "hu",
            "no",
            "vi",
            "bn",
            "th",
            "he",
            "ka",
            "id",
            "te",
            "gu",
            "kn",
            "ml",
            "mr",
            "pa",
          ],
        },
        "sonic-turbo": {
          name: "Sonic Turbo",
          usdPerMinute: 0.03,
          languages: ["en", "fr", "de", "es", "pt", "zh", "ja", "hi", "ko"],
        },
      },
    },
    deepgram: {
      name: "Deepgram",
      models: {
        "aura-2": {
          name: "Aura-2",
          usdPerMinute: 0.018,
          languages: [
            "en",
            "en-US",
            "en-PH",
            "en-GB",
            "en-AU",
            "es",
            "es-CO",
            "es-MX",
            "es-ES",
            "es-419",
            "es-AR",
            "nl",
            "nl-NL",
            "fr",
            "fr-FR",
            "de",
            "de-DE",
            "it",
            "it-IT",
            "ja",
            "ja-JP",
          ],
        },
      },
    },
    elevenlabs: {
      name: "ElevenLabs",
      models: {
        eleven_flash_v2: {
          name: "Eleven Flash v2",
          languages: ["en"],
          usdPerMinute: 0.09,
        },
        eleven_flash_v2_5: {
          name: "Eleven Flash v2.5",
          usdPerMinute: 0.09,
          languages: [
            "en",
            "ja",
            "zh",
            "de",
            "hi",
            "fr",
            "ko",
            "pt",
            "it",
            "es",
            "id",
            "nl",
            "tr",
            "fil",
            "pl",
            "sv",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "ru",
            "hu",
            "no",
            "vi",
          ],
        },
        eleven_multilingual_v2: {
          name: "Eleven Multilingual v2",
          usdPerMinute: 0.18,
          languages: [
            "en",
            "ja",
            "zh",
            "de",
            "hi",
            "fr",
            "ko",
            "pt",
            "it",
            "es",
            "id",
            "nl",
            "tr",
            "fil",
            "pl",
            "sv",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "ru",
          ],
        },
        eleven_turbo_v2: {
          name: "Eleven Turbo v2",
          languages: ["en"],
          usdPerMinute: 0.09,
        },
        eleven_turbo_v2_5: {
          name: "Eleven Turbo v2.5",
          usdPerMinute: 0.09,
          languages: [
            "en",
            "ja",
            "zh",
            "de",
            "hi",
            "fr",
            "ko",
            "pt",
            "it",
            "es",
            "id",
            "nl",
            "tr",
            "fil",
            "pl",
            "sv",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "ru",
            "hu",
            "no",
            "vi",
          ],
        },
        eleven_v3: {
          name: "Eleven v3",
          usdPerMinute: 0.18,
          languages: [
            "en",
            "ja",
            "zh",
            "de",
            "hi",
            "fr",
            "ko",
            "pt",
            "it",
            "es",
            "id",
            "nl",
            "tr",
            "fil",
            "pl",
            "sv",
            "bg",
            "ro",
            "ar",
            "cs",
            "el",
            "fi",
            "hr",
            "ms",
            "sk",
            "da",
            "ta",
            "uk",
            "ru",
            "hu",
            "no",
            "vi",
          ],
        },
      },
    },
    inworld: {
      name: "Inworld",
      models: {
        "inworld-tts-1.5-max": {
          name: "Realtime TTS 1.5 Max",
          usdPerMinute: 0.021,
          languages: [
            "en",
            "zh",
            "ja",
            "ko",
            "ru",
            "it",
            "es",
            "pt",
            "fr",
            "de",
            "pl",
            "nl",
            "hi",
            "he",
            "ar",
          ],
        },
        "inworld-tts-1.5-mini": {
          name: "Realtime TTS 1.5 Mini",
          usdPerMinute: 0.009,
          languages: [
            "en",
            "zh",
            "ja",
            "ko",
            "ru",
            "it",
            "es",
            "pt",
            "fr",
            "de",
            "pl",
            "nl",
            "hi",
            "he",
            "ar",
          ],
        },
        "inworld-tts-2": {
          name: "Realtime TTS 2.0",
          usdPerMinute: 0.015,
          languages: [
            "en",
            "zh",
            "ja",
            "ko",
            "ru",
            "it",
            "es",
            "pt",
            "fr",
            "de",
            "pl",
            "nl",
            "hi",
            "he",
            "ar",
          ],
        },
      },
    },
    rime: {
      name: "Rime",
      models: {
        arcana: {
          name: "Arcana",
          usdPerMinute: 0.024,
          languages: ["en", "es", "fr", "de", "hi", "he", "ja", "pt", "ar"],
        },
        coda: {
          name: "Coda",
          languages: ["en", "es", "fr", "de", "pt", "ja"],
          usdPerMinute: 0.03,
        },
        mist: { name: "Mist", languages: ["en"], usdPerMinute: 0.018 },
        mistv2: {
          name: "Mist v2",
          languages: ["en", "es", "fr", "de"],
          usdPerMinute: 0.018,
        },
        mistv3: {
          name: "Mist v3",
          usdPerMinute: 0.018,
          languages: ["en", "es", "fr", "de", "hi", "xAI"],
        },
      },
    },
    xai: {
      name: "xAI",
      models: {
        "tts-1": { name: "Text to Speech", usdPerMinute: 0.009 },
      },
    },
  },
}
